### PR TITLE
gh-pages search now works, and the yak shaving it took to get there

### LINKED ISSUE #107: pages search does not work
I tried searching just github pages in our internal installation, but I get no search results.

### PR DESCRIPTION
**Pull request by marcesher**
1) Fixes gh-pages search by replacing instances of "gh page" with "gh_page". "gh_page". Fixes #107

2) Updates README with correct instructions for several commands

3) Bumps version for grunt-bower-task, to fix a bug in the previous
version with bower interaction

4) Copies app.js into dist directory on grunt default, to aid in
front-end debugging. Without it: :rage:

### CODE REVIEW

File: Vagrantfile [hunk 1]
```diff
@@ -2,11 +2,9 @@
 # vi: set ft=ruby :
 
 Vagrant.configure("2") do |config|
-  # vbox name
-  config.vm.box = "centos_6_5_64"
 
-  # vbox url
-  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"
```
Comment (marcesher) [inline Vagrantfile]: This box has problems I could not resolve. Guest additions would not install, causing the /vagrant dir not to mount, causing it to be useless.

File: client/Gruntfile.js [hunk 2]
```diff
@@ -157,6 +157,8 @@ module.exports = function(grunt) {
                         "*.xml",
                         'index.html',
                         'static-test.html',
+                        //simplify debugging
+                        'static/js/app.js',
```
Comment (marcesher) [inline client/Gruntfile.js]: seriously don't know how any of you worked on the javascript without this

File: client/package.json [hunk 3]
```diff
@@ -31,7 +31,7 @@
   "devDependencies": {
     "grunt": "latest",
     "grunt-autoprefixer": "latest",
-    "grunt-bower-task": "~0.3.2",
+    "grunt-bower-task": "~0.4.x",
```
Comment (marcesher) [inline client/package.json]: the internet told me to do this, to get around a build error in `grunt vendor`

**Comment by marcesher** [comment]
@dgreisen-cfpb @m3brown I wanted to make sure you saw this PR.

File: client/dist/static/js/app.js [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+    if (highlight && highlight.title) {
+        cleanedData.title = highlight.title[0];
+    }
+    if (highlight && highlight.content) {
+        cleanedData.content = highlight.content[0];
+    }
+
+    return cleanedData;
+
+}
```
Comment (imuchnik) [inline client/dist/static/js/app.js]: Do we need to check in the dist directory? Could we not generate it on deploy?

Comment (marcesher) [inline client/dist/static/js/app.js]: I'll leave the decision on checking in dist/ to y'all.

What this specifically does though is ensure that app.js also gets copied to dist/, so that sourcemap works and it's easy to debug the JS during development. This is a developer-time enhancement and has no effect on runtime. If there's a better way, I'm all ears. For me, the problem it solved was that during development, I was forced to work with the minified JS and that was not OK for debugging.

**Comment by OrlandoSoto** [comment]
if someone could merge this? I would love to give it a spin and search gh-pages for the dev-manual :boom: this is great!
